version: '3.7'

services:  

  dev:
    container_name: "javascript_boilerplate_dev"
    build:
      context: .
      target: dev
    # env_file:
      # - ./local.env
    environment:
      - APP_PORT=3000
      - NODE_ENV=development      
    volumes:
      - ./src:/app/src      
    command: npm run serve
    ports:
      - '3000:3000'
    links:
      - db:db

  production:
    container_name: "javascript_boilerplate_production"
    build:
      context: .
      target: release
    # env_file:
      # - ./production.env
    environment:
      - APP_PORT=8000
      - NODE_ENV=production     
    command: npm run serve
    ports:
      - '8000:8000'    

  test:
    container_name: "javascript_boilerplate_test"
    build:
      context: .
      target: dev
    environment:
      - APP_PORT=3000
      - NODE_ENV=test      
    volumes:
      - ./src:/app/src      
    command: npm run test

  db:
    build:
      context: .
    container_name: "postgres_dev"  
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=Doe_passwordd
      - POSTGRES_DB=db_name
    ports:
      - "54320:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    # env_file:
    #   - ./dev_db.env